[project]
name = "train-unsloth"
version = "0.1.0"
description = "A CLI to train LLM using Unsloth framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.15.1",
    "tqdm",
    "Pillow",
    "unsloth==2026.1.2",
    "orjson",
    "vllm>=0.13.0",
    "more-itertools>=10.8.0",
    "wandb>=0.23.1",
    # pin torchao to 0.14.1, compatible with torch 2.9.0
    # See https://github.com/pytorch/ao/issues/2919
    "torchao==0.14.1",
    "qwen-vl-utils==0.0.14",
]
